title: "マークアップ言語シリーズ: Lesson 0 Visual Studio Codeを導入してみよう"
summary: "これからプログラミング学習を始められる方に向けての、web開発、フロントエンド開発をするための、最も優しい基本をまとめました。Visual Studio Codeをこれから新しく導入したい人に向けた教材です。"
topics: ["markdown", "vscode", "texteditor", "frontend"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter0
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - chapter6